# AUTO-GENERATED by generate_harness.py
ADA_SRC = src/use_after_free.adb src/null_pointer.adb src/division_by_zero.adb src/vulnerable_parser.adb src/integer_overflow.adb
C_SRC = harness.c
TARGET = fuzz_target

all: $(TARGET)

$(TARGET): $(ADA_SRC) $(C_SRC)
	@echo "Compiling Ada sources..."
	gnatmake -c $(ADA_SRC) -O2
	@echo "Compiling C harness with AFL++..."
	afl-gcc -c $(C_SRC) -o harness.o
	@echo "Linking..."
	gcc -no-pie -o $(TARGET) harness.o `find . -name '*.o' ! -name 'harness.o'` -lgnarl -lgnat -lm -lpthread -ldl
	@echo "Build complete: $(TARGET)"

clean:
	rm -f *.o *.ali $(TARGET)

.PHONY: all clean
