#!/usr/bin/env python3
"""
Universal Ada Fuzzing Harness Generator.
Scans src/*.ads for pragma Export(C,...) and generates:
  - harness.c  (C wrapper for AFL++)
  - Makefile   (build rules)
  - testcases/ (seed files)
"""
import os, re, sys, glob

SRC_DIR = "src"
TESTCASES_DIR = "testcases"

# Regex patterns
EXPORT_RE = re.compile(
    r'pragma\s+Export\s*\(\s*C\s*,\s*(\w+)\s*,\s*"([^"]+)"\s*\)',
    re.IGNORECASE
)
PROC_RE = re.compile(
    r'^\s*(procedure|function)\s+(\w+)\s*\(([^)]*)\)\s*;?\s*$',
    re.IGNORECASE | re.MULTILINE
)

def parse_ads(filepath):
    """Extract exported functions and their signatures from .ads file."""
    with open(filepath) as f:
        content = f.read()
    
    exports = {}
    for m in EXPORT_RE.finditer(content):
        ada_name, c_name = m.group(1), m.group(2)
        exports[c_name] = ada_name
    
    signatures = {}
    for m in PROC_RE.finditer(content):
        kind, name, params = m.group(1).lower(), m.group(2), m.group(3).strip()
        signatures[name] = (kind, params)
    
    return exports, signatures

def classify_params(params_str):
    """Classify parameters into supported patterns."""
    if not params_str:
        return "no_params"
    
    p = params_str.lower()
    if "system.address" in p and ("size_t" in p or "interfaces.c.size_t" in p):
        return "buffer"
    if any(t in p for t in ["integer", "character", "boolean", "float"]):
        return "scalars"
    return "unknown"

def generate_harness_c(all_exports):
    """Generate harness.c with fuzz wrappers for all exported functions."""
    lines = [
        '/* AUTO-GENERATED by generate_harness.py - DO NOT EDIT */',
        '#include <stdio.h>',
        '#include <stdlib.h>',
        '#include <stdint.h>',
        '#include <string.h>',
        '',
    ]
    
    for c_name, (kind, params, sig_type) in all_exports:
        if sig_type == "buffer":
            lines.append(f'extern void {c_name}(void *data, size_t len);')
        elif sig_type == "no_params":
            lines.append(f'extern void {c_name}(void);')
        else:
            lines.append(f'/* extern ??? {c_name}(...) - unsupported signature */')
    
    lines.append('')
    lines.append('int main(int argc, char **argv) {')
    lines.append('    if (argc < 2) { fprintf(stderr, "Usage: %s <input>\\n", argv[0]); return 1; }')
    lines.append('    FILE *f = fopen(argv[1], "rb");')
    lines.append('    if (!f) { perror("fopen"); return 1; }')
    lines.append('    fseek(f, 0, SEEK_END);')
    lines.append('    long file_size = ftell(f);')
    lines.append('    fseek(f, 0, SEEK_SET);')
    lines.append('    uint8_t *buffer = malloc(file_size > 0 ? file_size : 1);')
    lines.append('    if (file_size > 0) fread(buffer, 1, file_size, f);')
    lines.append('    fclose(f);')
    lines.append('')
    
    for c_name, (kind, params, sig_type) in all_exports:
        lines.append(f'    /* Fuzzing: {kind} {c_name} */')
        if sig_type == "buffer":
            lines.append(f'    {c_name}(buffer, (size_t)file_size);')
        elif sig_type == "no_params":
            lines.append(f'    {c_name}();')
        else:
            lines.append(f'    /* {c_name}: unsupported signature, skipping */')
        lines.append('')
    
    lines.append('    free(buffer);')
    lines.append('    return 0;')
    lines.append('}')
    lines.append('')
    
    return '\n'.join(lines)

def generate_makefile(adb_files):
    """Generate Makefile for building all Ada files + harness."""
    ada_list = ' '.join(adb_files)
    return f"""# AUTO-GENERATED by generate_harness.py
ADA_SRC = {ada_list}
C_SRC = harness.c
TARGET = fuzz_target

all: $(TARGET)

$(TARGET): $(ADA_SRC) $(C_SRC)
\t@echo "Compiling Ada sources..."
\tgnatmake -c $(ADA_SRC) -O2
\t@echo "Compiling C harness with AFL++..."
\tafl-gcc -c $(C_SRC) -o harness.o
\t@echo "Linking..."
\tgcc -no-pie -o $(TARGET) harness.o `find . -name '*.o' ! -name 'harness.o'` -lgnarl -lgnat -lm -lpthread -ldl
\t@echo "Build complete: $(TARGET)"

clean:
\trm -f *.o *.ali $(TARGET)

.PHONY: all clean
"""

def generate_seeds(all_exports):
    """Create seed files for each exported function."""
    os.makedirs(TESTCASES_DIR, exist_ok=True)
    for c_name, (kind, params, sig_type) in all_exports:
        seed_path = os.path.join(TESTCASES_DIR, f"{c_name}_seed.bin")
        if sig_type == "buffer":
            with open(seed_path, 'wb') as f:
                # Разные seeds для разных уязвимостей
                if c_name == "process_buffer":
                    f.write(b'\xFF' * 10)  # Integer overflow
                elif c_name == "process_data":
                    f.write(b'\xFF\x00' * 5)  # Null pointer trigger
                elif c_name == "process_memory":
                    f.write(b'\xDE\xAD' * 5)  # Use-after-free
                elif c_name == "calculate":
                    f.write(b'\x01\x00' * 5)  # Division by zero (1-1=0)
                else:
                    f.write(b'X')
        elif sig_type == "no_params":
            with open(seed_path, 'wb') as f:
                f.write(b'\x00')
        else:
            with open(seed_path, 'wb') as f:
                f.write(b'A')
        print(f"  Created seed: {seed_path}")

def main():
    print("=== Ada Fuzzing Harness Generator ===")
    
    ads_files = glob.glob(os.path.join(SRC_DIR, "*.ads"))
    if not ads_files:
        print(f"ERROR: No .ads files found in {SRC_DIR}/")
        sys.exit(1)
    
    print(f"Found {len(ads_files)} spec file(s): {ads_files}")
    
    all_exports = []
    adb_files_for_makefile = []
    
    for ads_file in ads_files:
        adb_file = ads_file.replace('.ads', '.adb')
        if not os.path.exists(adb_file):
            print(f"WARNING: No body file for {ads_file}, skipping")
            continue
        
        adb_files_for_makefile.append(adb_file)
        
        exports, signatures = parse_ads(ads_file)
        print(f"\nParsing {ads_file}:")
        
        for c_name, ada_name in exports.items():
            if ada_name in signatures:
                kind, params = signatures[ada_name]
                sig_type = classify_params(params)
                print(f"  Exported: {kind} {ada_name} -> {c_name} (type: {sig_type})")
                all_exports.append((c_name, (kind, params, sig_type)))
            else:
                print(f"  WARNING: {ada_name} exported but signature not found")
                all_exports.append((c_name, (kind, "", "unknown")))
    
    if not all_exports:
        print("\nERROR: No exported functions found!")
        sys.exit(1)
    
    print(f"\n=== Generating harness.c ({len(all_exports)} function(s)) ===")
    harness_code = generate_harness_c(all_exports)
    with open("harness.c", 'w') as f:
        f.write(harness_code)
    print("  Created harness.c")
    
    print(f"\n=== Generating Makefile ===")
    makefile = generate_makefile(adb_files_for_makefile)
    with open("Makefile", 'w') as f:
        f.write(makefile)
    print("  Created Makefile")
    
    print(f"\n=== Generating seed files ===")
    generate_seeds(all_exports)
    
    print(f"\n=== DONE! ===")
    print(f"Total exported functions: {len(all_exports)}")
    print(f"Run: make && afl-fuzz -i {TESTCASES_DIR}/ -o findings/ -- ./fuzz_target @@")

if __name__ == "__main__":
    main()
